// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package querier

import (
	"time"

	"github.com/google/uuid"
)

type ErrorMessage struct {
	ID          int64     `json:"id"`
	ServiceName string    `json:"service_name"`
	PayloadName string    `json:"payload_name"`
	PayloadData string    `json:"payload_data"`
	MessageID   string    `json:"message_id"`
	Topic       string    `json:"topic"`
	OrderingKey string    `json:"ordering_key"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type User struct {
	ID            uuid.UUID `json:"id"`
	Email         string    `json:"email"`
	Username      string    `json:"username"`
	Password      string    `json:"password"`
	AttemptLeft   int32     `json:"attempt_left"`
	OtpCode       int64     `json:"otp_code"`
	PhoneNumber   string    `json:"phone_number"`
	Status        string    `json:"status"`
	MainImageUrl  string    `json:"main_image_url"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	MainImagePath string    `json:"main_image_path"`
}

type UserImage struct {
	ID        uuid.UUID `json:"id"`
	ImageUrl  string    `json:"image_url"`
	ImagePath string    `json:"image_path"`
	IsMain    bool      `json:"is_main"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
