// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package querier

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateErrorMessage(ctx context.Context, arg CreateErrorMessageParams) (ErrorMessage, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserImage(ctx context.Context, arg CreateUserImageParams) (UserImage, error)
	DeleteErrorMessage(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserImage(ctx context.Context, id uuid.UUID) error
	FindErrorMessage(ctx context.Context, arg FindErrorMessageParams) ([]ErrorMessage, error)
	FindUserByIdForUpdate(ctx context.Context, id uuid.UUID) (User, error)
	FindUserImageByIdForUpdate(ctx context.Context, id uuid.UUID) (UserImage, error)
	FindUserMainImageByUserIdForUpdate(ctx context.Context, userID uuid.UUID) (UserImage, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserImage(ctx context.Context, arg UpdateUserImageParams) (UserImage, error)
	UpdateUserMainImage(ctx context.Context, arg UpdateUserMainImageParams) (User, error)
}

var _ Querier = (*Queries)(nil)
