// Code generated by MockGen. DO NOT EDIT.
// Source: service/notification_service.go

// Package mock_svc is a generated GoMock package.
package mock_svc

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNotificationSvc is a mock of NotificationSvc interface.
type MockNotificationSvc struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationSvcMockRecorder
}

// MockNotificationSvcMockRecorder is the mock recorder for MockNotificationSvc.
type MockNotificationSvcMockRecorder struct {
	mock *MockNotificationSvc
}

// NewMockNotificationSvc creates a new mock instance.
func NewMockNotificationSvc(ctrl *gomock.Controller) *MockNotificationSvc {
	mock := &MockNotificationSvc{ctrl: ctrl}
	mock.recorder = &MockNotificationSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationSvc) EXPECT() *MockNotificationSvcMockRecorder {
	return m.recorder
}

// ListenForEmailTopic mocks base method.
func (m *MockNotificationSvc) ListenForEmailTopic(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenForEmailTopic", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListenForEmailTopic indicates an expected call of ListenForEmailTopic.
func (mr *MockNotificationSvcMockRecorder) ListenForEmailTopic(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenForEmailTopic", reflect.TypeOf((*MockNotificationSvc)(nil).ListenForEmailTopic), ctx)
}

// ListenForUserImageTopic mocks base method.
func (m *MockNotificationSvc) ListenForUserImageTopic(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenForUserImageTopic", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListenForUserImageTopic indicates an expected call of ListenForUserImageTopic.
func (mr *MockNotificationSvcMockRecorder) ListenForUserImageTopic(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenForUserImageTopic", reflect.TypeOf((*MockNotificationSvc)(nil).ListenForUserImageTopic), ctx)
}

// ListenForUserTopic mocks base method.
func (m *MockNotificationSvc) ListenForUserTopic(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenForUserTopic", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListenForUserTopic indicates an expected call of ListenForUserTopic.
func (mr *MockNotificationSvcMockRecorder) ListenForUserTopic(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenForUserTopic", reflect.TypeOf((*MockNotificationSvc)(nil).ListenForUserTopic), ctx)
}
