// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package user_db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserImage(ctx context.Context, arg CreateUserImageParams) (UserImage, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserImage(ctx context.Context, id uuid.UUID) error
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserById(ctx context.Context, id uuid.UUID) (User, error)
	FindUserImageById(ctx context.Context, id uuid.UUID) (UserImage, error)
	FindUserImagesByUserId(ctx context.Context, userID uuid.UUID) ([]UserImage, error)
	FindUserWithImages(ctx context.Context, id uuid.UUID) (FindUserWithImagesRow, error)
	FindUsers(ctx context.Context, arg FindUsersParams) ([]User, error)
	GetUsersPaginationCount(ctx context.Context, arg GetUsersPaginationCountParams) (int64, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserImage(ctx context.Context, arg UpdateUserImageParams) (UserImage, error)
	UpdateUserMainImage(ctx context.Context, arg UpdateUserMainImageParams) (User, error)
}

var _ Querier = (*Queries)(nil)
