# Build stage
FROM golang:1.18-alpine3.15 AS builder

WORKDIR /app
COPY ./ ./

RUN go mod tidy
RUN go build -o main wire_gen.go main.go

# Run stage
FROM alpine:3.15

WORKDIR /app
RUN apk update && apk add bash && apk --no-cache add tzdata
COPY --from=builder ./app/main ./
COPY ./app/app.env ./app/
COPY docs ./docs
COPY *.json ./
COPY start.sh ./

COPY db/migration ./db/migration

ENTRYPOINT [ "/app/start.sh", "/app/main" ]
