// Code generated by MockGen. DO NOT EDIT.
// Source: handler/notification_handler.go

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	context "context"
	http "net/http"
	reflect "reflect"

	chi "github.com/go-chi/chi/v5"
	gomock "github.com/golang/mock/gomock"
)

// MockNotificationHandler is a mock of NotificationHandler interface.
type MockNotificationHandler struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationHandlerMockRecorder
}

// MockNotificationHandlerMockRecorder is the mock recorder for MockNotificationHandler.
type MockNotificationHandlerMockRecorder struct {
	mock *MockNotificationHandler
}

// NewMockNotificationHandler creates a new mock instance.
func NewMockNotificationHandler(ctrl *gomock.Controller) *MockNotificationHandler {
	mock := &MockNotificationHandler{ctrl: ctrl}
	mock.recorder = &MockNotificationHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationHandler) EXPECT() *MockNotificationHandlerMockRecorder {
	return m.recorder
}

// ListenEvent mocks base method.
func (m *MockNotificationHandler) ListenEvent(ctx context.Context, isEndlessly bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListenEvent", ctx, isEndlessly)
}

// ListenEvent indicates an expected call of ListenEvent.
func (mr *MockNotificationHandlerMockRecorder) ListenEvent(ctx, isEndlessly interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenEvent", reflect.TypeOf((*MockNotificationHandler)(nil).ListenEvent), ctx, isEndlessly)
}

// Ping mocks base method.
func (m *MockNotificationHandler) Ping(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Ping", w, r)
}

// Ping indicates an expected call of Ping.
func (mr *MockNotificationHandlerMockRecorder) Ping(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockNotificationHandler)(nil).Ping), w, r)
}

// SetupUserRoutes mocks base method.
func (m *MockNotificationHandler) SetupUserRoutes(route *chi.Mux) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetupUserRoutes", route)
}

// SetupUserRoutes indicates an expected call of SetupUserRoutes.
func (mr *MockNotificationHandlerMockRecorder) SetupUserRoutes(route interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupUserRoutes", reflect.TypeOf((*MockNotificationHandler)(nil).SetupUserRoutes), route)
}
